### PR TITLE
Update donate.html

### PR DESCRIPTION
**Pull request by sunnankar**
Adding SSL and updating the URL.

### CODE REVIEW

**Comment by Techwolfy** [comment]
Thanks; I hadn't noticed that link had broken. However, would you mind adding a more descriptive commit message stating exactly what you changed? It's easy to see in the code, but it would be confusing when looking through the commit log.

**Comment by sunnankar** [comment]
Is that better or do you think it needs a new pull request?

**Comment by Techwolfy** [comment]
Apparently I can add comments to pull request merges, so that will be fine. Sorry for the delay, I'm still learning some of the collaborative features of Github.

Thanks for contributing! ^.^

**Comment by sunnankar** [comment]
Github is pretty cool but can take some getting used to. Glad to help!

**Pull request merged**
